const businessNames = [
    "Tech Solutions Inc.",
    "Green Earth",
    "Landscaping",
    "Cozy",
    "Coffee Shop",
    "Happy Paws",
    "Pet Care",
    "Creative Marketing",
    "Agency",
    "Global Travel",
    "Modern Fitness Gym",
    "Financial Planning Services",
    "Mountain View Bakery",
    "Crafty Corner Boutique",
    "Starlight Photography",
    "Reliable Plumbing",
    "Smart Tech Repairs",
    "Blooming Flowers",
    "Delicious", "Delights Catering",
    "efis",
    "OrbitQ",
    "Rakudo",
    "Orazo",
    " MELODW  ",
    "MELODIA",
    "Wlk1Pronto",
    "GESHTI",
    "AZA3USY",
    "MELODIAC",
    "Wlk1Pronto",
    "GESHTI",
    "AZABIJS",
    "ROBIBIZ",
    "MAZA",
    "li",
    "Bzness",
    "Aza",
    "BIZNA",
    "Azazon",
    "Zaza",
    "Almaz",
    "NAMORAa",
    "POPULAR",
    "lROSZ",
    "MEGA",
    "AK",
    "OZO",
    "BUSIEK",
    "MAQUINA",
    "maravello",
    "AQUA",
    "Iluvo",
    "Zentar",
    "Prava",
    "Zoboz",
    "AZALUNA",
    "AZASUN",
    "Gentaro",
    "Inspiraro",
    "TRANSFORMA",
    "Irio",
    "TEAMA7_",
    "ANAZAH",
    "Rotonzo",
    "Amazo",
    "Jin",
    "asivar",
    "ZENTR",
    "Afflux",
    "Sandia",
    "Zavir",
    "Emergi",
    "pIaoSZ",
    "MEGA",
    "Minni",
    "BUSIEK",
    "MAQUINA",
    "Maravello",
    "AQUA",
    "Isluvo",
    "AKIB",
    "ZOOM",
    "KONOM",
    "Azaro",
    "ASZARO",
    "SwagBl-",
    "RAZAN",
    "Itsemd",
    "Regen",
    "Zoze",
    "IAA7_A",
 "DINAMIK",
 "INTQACTIVO",
 "SIMUZA",
 "Konect",
 "Topaz",
 "LA'KOR",
 "CYBERSOUL",
 "Azarex",
 "REDBIZ",
 "Dornir•uorl",
 "Azadar",
 "Azo",
 "Kaib",
 "jfoura",
 "AZAROSO",
 "ACASA",
 "SONIK",
 "Nuran",
 "Universus",
 "CAMAT",
 "GEVAL",
 "Manzur",
 "ELECTRICIDO",
 "InTonixo",
 "Akay",
 "VARJ",
 "GEZA",
"MODELIZA",
"Supremus",
"Aswa",
"Landor",
"Ebiz",
"ODORO",
"Burna",
"Alza",
"sarilll",
];

console.log(businessNames.length)
var RandonNames = Math.floor(Math.random()*businessNames.length)
var RandonName = businessNames[RandonNames]
document.getElementById("inner").innerHTML = RandonName